var wonders = [
	{title: 'Great Pyramid of Giza', img: 'http://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Kheops-Pyramid.jpg/1024px-Kheops-Pyramid.jpg', copy1: 'The Great Pyramid of Giza (also known as the Pyramid of Khufu or the Pyramid of Cheops) is the oldest and largest of the three pyramids in the Giza Necropolis bordering what is now El Giza, Egypt. It is the oldest of the Seven Wonders of the Ancient World, and the only one to remain largely intact.', copy2: 'Based on a mark in an interior chamber naming the work gang and a reference to fourth dynasty Egyptian Pharaoh Khufu,[1][2] Egyptologists believe that the pyramid was built as a tomb over a 10 to 20-year period concluding around 2560 BC. Initially at 146.5 metres (481 feet), the Great Pyramid was the tallest man-made structure in the world for over 3,800 years. Originally, the Great Pyramid was covered by casing stones that formed a smooth outer surface; what is seen today is the underlying core structure. Some of the casing stones that once covered the structure can still be seen around the base. There have been varying scientific and alternative theories about the Great Pyramid\'s construction techniques. Most accepted construction hypotheses are based on the idea that it was built by moving huge stones from a quarry and dragging and lifting them into place.'},
	{title: 'Hanging Gardens of Babylon', img: 'http://upload.wikimedia.org/wikipedia/commons/a/ae/Hanging_Gardens_of_Babylon.jpg', copy1: 'The Hanging Gardens of Babylon were one of the Seven Wonders of the Ancient World, and the only one whose location has not been definitely established. Traditionally they were said to have been built in the ancient city of Babylon, near present-day Hillah, Babil province, in Iraq. The Babylonian priest Berossus, writing in about 290 BC and quoted later by Josephus, attributed the gardens to the Neo-Babylonian king Nebuchadnezzar II, who ruled between 605 and 562 BC. There are no extant Babylonian texts which mention the gardens, and no definitive archaeological evidence has been found in Babylon.[1][2]', copy2: 'According to one legend, Nebuchadnezzar II built the Hanging Gardens for his Median wife, Queen Amytis, because she missed the green hills and valleys of her homeland. He also built a grand palace that came to be known as \'The Marvel of the Mankind\'.'},
	{title: 'Temple of Artemis', img: 'http://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Miniaturk_009.jpg/800px-Miniaturk_009.jpg', copy1: 'The Temple of Artemis (Greek: Ἀρτεμίσιον, or Artemision), also known less precisely as the Temple of Diana, was a Greek temple dedicated to the goddess Artemis and was one of the Seven Wonders of the Ancient World. It was located in Ephesus (near the modern town of Selçuk in present-day Turkey), and was completely rebuilt three times before its eventual destruction in 401.[1] Only foundations and sculptural fragments of the latest of the temples at the site remain.', copy2: 'The first sanctuary (temenos) antedated the Ionic immigration by many years, and dates to the Bronze Age. Callimachus, in his Hymn to Artemis, attributed it to the Amazons. In the 7th century BC, the old temple was destroyed by a flood. Its reconstruction began around 550 BC, under the Cretan architect Chersiphron and his son Metagenes, at the expense of Croesus of Lydia: the project took 10 years to complete, only to be destroyed in an act of arson by Herostratus. It was later rebuilt.'},
	{title: 'Statue of Zeus at Olympia', img: 'http://upload.wikimedia.org/wikipedia/commons/c/c6/Statue_of_Zeus.jpg', copy1: 'The Statue of Zeus at Olympia was a giant seated figure, about 13 m (43 ft) tall,[1] made by the Greek sculptor Phidias around 435 BC at the sanctuary of Olympia, Greece, and erected in the Temple of Zeus there. A sculpture of ivory plates and gold panels over a wooden framework, it represented the god Zeus sitting on an elaborate cedarwood throne ornamented with ebony, ivory, gold and precious stones. It was regarded as one of the Seven Wonders of the Ancient World until its eventual loss and destruction during the 5th century AD.[2] No copy of the statue has ever been found, and details of its form are known only from ancient Greek descriptions and representations on coins.', copy2: 'The great seated statue as fashioned by Phidias occupied half the width of the aisle of the temple built to house it. "It seems that if Zeus were to stand up," the geographer Strabo noted early in the 1st century BC, "he would unroof the temple."[3] The Zeus was a chryselephantine sculpture, made with ivory and gold panels on a wooden substructure. No copy in marble or bronze has survived, though there are recognizable but only approximate versions on coins of nearby Elis and on Roman coins and engraved gems.[4]'},
	{title: 'Mausoleium at Halicarnassus', img: 'http://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Mausoleum_of_Halicarnassus_2009.jpg/1024px-Mausoleum_of_Halicarnassus_2009.jpg', copy1: 'The Mausoleum at Halicarnassus or Tomb of Mausolus[1] (Greek: Μαυσωλείο της Αλικαρνασσού, modern Turkish: Halikarnas Mozolesi) was a tomb built between 353 and 350 BC at Halicarnassus (present Bodrum, Turkey) for Mausolus, a satrap in the Persian Empire, and Artemisia II of Caria, who was both his wife and his sister. The structure was designed by the Greek architects Satyros and Pythius of Priene.[2][3]', copy2: 'The Mausoleum was approximately 45 m (148 ft) in height, and the four sides were adorned with sculptural reliefs, each created by one of four Greek sculptors — Leochares, Bryaxis, Scopas of Paros and Timotheus.[4] The finished structure of the mausoleum was considered to be such an aesthetic triumph that Antipater of Sidon identified it as one of his Seven Wonders of the Ancient World. It was destroyed through many earthquakes from 12th century to 15th century. [5][6] [7]'},
	{title: 'Colossus of Rhodes', img: 'http://upload.wikimedia.org/wikipedia/commons/5/5f/Colosse_de_Rhodes_%28Barclay%29.jpg', copy1: 'The Colossus of Rhodes (Ancient Greek: Ὁ Κολοσσὸς Ῥόδιος Ho Kolossòs Rhódios) was a statue of the Greek god Helios, erected in the city of Rhodes, on the Greek island of the same name, by Chares of Lindos in 280 BC. It is considered one of the Seven Wonders of the Ancient World. It was constructed to celebrate Rhodes victory over the ruler of Cyprus, Antigonus I Monophthalmus, whose son unsuccessfully besieged Rhodes in 305 BC. Before its destruction in the earthquake of 226 BC, the Colossus of Rhodes stood over 30 meters (98 feet) high,[1] making it one of the tallest statues of the ancient world.[2]', copy2: 'In 304 BC a relief force of ships sent by Ptolemy arrived, and Antigonus\'s army abandoned the siege, leaving most of their siege equipment. To celebrate their victory, the Rhodians sold the equipment left behind for 300 talents[3] and decided to use the money to build a colossal statue of their patron god, Helios. Construction was left to the direction of Chares, a native of Lindos in Rhodes, who had been involved with large-scale statues before. His teacher, the sculptor Lysippos, had constructed a 22 meters (72 feet) high[4] bronze statue of Zeus at Tarentum.'},
	{title: 'Lighthouse of Alenandria', img: 'http://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Lighthouse_-_Thiersch.gif/800px-Lighthouse_-_Thiersch.gif', copy1: 'The Lighthouse of Alexandria, sometimes called the Pharos of Alexandria (in Ancient Greek, ὁ Φάρος τῆς Ἀλεξανδρείας), was a lofty tower built by the Ptolemaic Kingdom between 280 and 247 BC and between 393 and 450 ft (120 and 137 m) tall. It was one of the tallest man-made structures on Earth for many centuries, and was regarded as one of the Seven Wonders of the Ancient World. Badly damaged by three earthquakes between 956 and 1323, it then became an abandoned ruin. It was the third longest surviving ancient wonder (after the Mausoleum at Halicarnassus and the still extant Great Pyramid of Giza) until in 1480 the last of its remnant stones were used to build the Citadel of Qaitbay on the site. In 1994, French archaeologists discovered some remains of the lighthouse on the floor of Alexandria\'s Eastern Harbour.[1]', copy2: 'Pharos was a small island just off the coast of the Nile Delta\'s western edge. In 332 BC when Alexander the Great founded the city of Alexandria on an isthmus opposite to Pharos, he caused the island to be united to the coast by a mole[2] nearly a mile long (1260 m) called the Heptastadion ("seven stadia"—a stadium was a Greek unit of length measuring approximately 180 m). The east side of the mole became the Great Harbour, now an open bay; on the west side lay the port of Eunostos, with its inner basin Kibotos, now vastly enlarged to form the modern harbour. Today\'s city development lying between the present Grand Square and the modern Ras al-Tiin quarter is built on the silt which gradually widened and obliterated this mole, and Ras al-Tiin represents all that is left of the island of Pharos, the site of the lighthouse at its eastern point having been weathered away by the sea.'},
];

wonders.forEach(function(wonder) {
	document.body.innerHTML += 
		'<h2>' + wonder.title + '</h2>' 
		+ '<div class="container">'
			+ '<div class="row">'
				+ '<div class="col-md-4 col-md-offset-4">'
				+ '<img src="' + wonder.img + '">'
				+ '</div>'
			+ '</div>'
			+ '<div class="row">'
				+ '<div class="col-md-6">'
				+ '<p>' + wonder.copy1 + '</p>'
				+ '</div>'
				+ '<div class="col-md-6">'
				+ '<p>' + wonder.copy2 + '</p>'
				+ '</div>'
			+ '</div>'
		+ '</div>'

	;
});